<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AspireForm</RootNamespace>
    <AssemblyName>AspireForm</AssemblyName>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>aspireform</ToolCommandName>
    <PackageId>AspireForm</PackageId>
    <Version>0.1.0</Version>
    <Authors>AspireForm</Authors>
    <Description>Declarative construction and configuration of .NET Aspire applications.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="YamlDotNet" Version="18.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
