using AspireForm.ApiCatalog;
using AspireForm.EntityCatalog;
using AwesomeAssertions;
using Xunit;

namespace AspireForm.Tests.ApiCatalog;

public sealed class EndpointEmitterTests
{
    private static EndpointCatalog EmptyCatalog() => new([], []);

    private static EndpointCatalog CatalogOf(params EndpointInfo[] endpoints) => new(endpoints, []);

    private static EndpointInfo SimpleEndpoint(
        string type = "BooksHandler",
        string method = "GetBooks",
        string route = "/books",
        string httpMethod = "GET",
        string? summary = null,
        string? authPolicy = null,
        string[]? tags = null) =>
        new(type, method, route, httpMethod, summary, authPolicy,
            (IReadOnlyList<string>)(tags ?? []), [], [], $"{type}.cs");

    [Fact]
    public void Render_emits_valid_csharp_with_empty_method_body_for_empty_catalog()
    {
        var src = EndpointEmitter.Render(EmptyCatalog(), "Demo");
        src.Should().Contain("// <auto-generated />");
        src.Should().Contain("// aspireform: managed block=\"api-endpoints\"");
        src.Should().Contain("namespace Demo;");
        src.Should().Contain("internal static class AspireFormEndpointExtensions");
        src.Should().Contain("public static WebApplication MapAspireFormEndpoints(this WebApplication app)");
        src.Should().Contain("return app;");
    }

    [Fact]
    public void Render_emits_MapGet_for_GET_endpoint()
    {
        var src = EndpointEmitter.Render(CatalogOf(SimpleEndpoint()), "Demo");
        src.Should().Contain("app.MapGet(\"/books\", BooksHandler.GetBooks)");
        src.Should().Contain(".WithName(\"GetBooks\")");
    }

    [Fact]
    public void Render_emits_WithSummary_when_ApiSummary_present()
    {
        var ep = SimpleEndpoint(summary: "Returns all books");
        var src = EndpointEmitter.Render(CatalogOf(ep), "Demo");
        src.Should().Contain(".WithSummary(\"Returns all books\")");
    }

    [Fact]
    public void Render_emits_AllowAnonymous_when_policy_is_anonymous()
    {
        var ep = SimpleEndpoint(authPolicy: "anonymous");
        var src = EndpointEmitter.Render(CatalogOf(ep), "Demo");
        src.Should().Contain(".AllowAnonymous()");
        src.Should().NotContain("RequireAuthorization");
    }

    [Fact]
    public void Render_emits_RequireAuthorization_when_policy_is_not_anonymous()
    {
        var ep = SimpleEndpoint(authPolicy: "admin");
        var src = EndpointEmitter.Render(CatalogOf(ep), "Demo");
        src.Should().Contain(".RequireAuthorization(\"admin\")");
        src.Should().NotContain("AllowAnonymous");
    }

    [Fact]
    public void Render_emits_WithTags_when_ApiTag_present()
    {
        var ep = SimpleEndpoint(tags: ["Books", "Public"]);
        var src = EndpointEmitter.Render(CatalogOf(ep), "Demo");
        src.Should().Contain(".WithTags(\"Books\", \"Public\")");
    }

    [Fact]
    public void Render_emits_app_Map_for_unknown_http_method()
    {
        var ep = SimpleEndpoint(httpMethod: "HEAD");
        var src = EndpointEmitter.Render(CatalogOf(ep), "Demo");
        src.Should().Contain("app.Map(\"/books\", BooksHandler.GetBooks)");
    }

    [Fact]
    public void Render_uses_supplied_rootNamespace()
    {
        var src = EndpointEmitter.Render(EmptyCatalog(), "MyApp.Api");
        src.Should().Contain("namespace MyApp.Api;");
    }
}
