using System.Text;

namespace AspireForm.ApiCatalog;

/// <summary>Renders a managed <c>_Endpoints.g.cs</c> file from an <see cref="EndpointCatalog"/> snapshot.</summary>
public static class EndpointEmitter
{
    /// <summary>Renders the content of <c>_Endpoints.g.cs</c> from the supplied catalog.</summary>
    /// <param name="catalog">The endpoint catalog snapshot to render.</param>
    /// <param name="rootNamespace">The root namespace of the target Web project (used for the generated class namespace).</param>
    /// <returns>The rendered file content as a string.</returns>
    public static string Render(EndpointCatalog catalog, string rootNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// aspireform: managed block=\"api-endpoints\"");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine();
        sb.Append("namespace ").Append(rootNamespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Extension methods generated by AspireForm from [ApiEndpoint]-decorated methods.</summary>");
        sb.AppendLine("internal static class AspireFormEndpointExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registers all [ApiEndpoint]-decorated handlers discovered by AspireForm.</summary>");
        sb.AppendLine("    public static WebApplication MapAspireFormEndpoints(this WebApplication app)");
        sb.AppendLine("    {");

        foreach (var ep in catalog.Endpoints.OrderBy(e => e.Route, StringComparer.Ordinal).ThenBy(e => e.HttpMethod, StringComparer.Ordinal))
        {
            sb.Append("        // ").Append(ep.HandlerTypeName).Append('.').Append(ep.MethodName)
              .Append(" — ").Append(ep.HttpMethod).Append(' ').AppendLine(ep.Route);

            var mapMethod = ep.HttpMethod.ToUpperInvariant() switch
            {
                "GET" => "MapGet",
                "POST" => "MapPost",
                "PUT" => "MapPut",
                "PATCH" => "MapPatch",
                "DELETE" => "MapDelete",
                _ => "Map",
            };

            sb.Append("        app.").Append(mapMethod).Append("(\"").Append(ep.Route).Append("\", ")
              .Append(ep.HandlerTypeName).Append('.').Append(ep.MethodName).AppendLine(")");

            // Fluent chain — always emit WithName.
            sb.Append("            .WithName(\"").Append(ep.MethodName).AppendLine("\")");

            if (!string.IsNullOrEmpty(ep.Summary))
            {
                sb.Append("            .WithSummary(\"").Append(ep.Summary.Replace("\"", "\\\"")).AppendLine("\")");
            }

            if (!string.IsNullOrEmpty(ep.AuthPolicy))
            {
                if (string.Equals(ep.AuthPolicy, "anonymous", StringComparison.OrdinalIgnoreCase))
                {
                    sb.AppendLine("            .AllowAnonymous()");
                }
                else
                {
                    sb.Append("            .RequireAuthorization(\"").Append(ep.AuthPolicy).AppendLine("\")");
                }
            }

            if (ep.Tags.Count > 0)
            {
                var tags = string.Join(", ", ep.Tags.Select(t => $"\"{t}\""));
                sb.Append("            .WithTags(").Append(tags).AppendLine(")");
            }

            // End the fluent chain with a semicolon on the last line.
            // Replace the trailing newline on the last fluent call.
            // Approach: mark the last AppendLine above with a semicolon by replacing the last newline.
            // Simpler: just emit a standalone semicolon on its own line.
            sb.AppendLine("            ;");
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
