using System.Text;
using Catalog = AspireForm.EntityCatalog.EntityCatalog;

namespace AspireForm.Providers.EfData;

/// <summary>Emits a DbContext class with <c>DbSet&lt;T&gt;</c> per entity and an <c>OnModelCreating</c> override containing any relationship configuration requiring Fluent API (e.g., <c>OnDelete</c>).</summary>
public static class DbContextEmitter
{
    /// <summary>Renders the DbContext file contents.</summary>
    public static string Render(string contextName, string contextNamespace, Catalog catalog)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by AspireForm ef-data /> Do not edit by hand inside the managed region.");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.Append("namespace ").Append(contextNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public class ").Append(contextName).AppendLine(" : DbContext");
        sb.AppendLine("{");
        sb.Append("    public ").Append(contextName).Append("(DbContextOptions<").Append(contextName).AppendLine("> options) : base(options) { }");
        sb.AppendLine();

        foreach (var e in catalog.Entities.OrderBy(e => e.Name, StringComparer.Ordinal))
        {
            sb.Append("    public DbSet<").Append(e.Name).Append("> ").Append(Pluralise(e.Name)).AppendLine(" { get; set; } = null!;");
        }

        var fluent = CollectFluentConfig(catalog);
        if (fluent.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
            sb.AppendLine("    {");
            sb.AppendLine("        base.OnModelCreating(modelBuilder);");
            foreach (var line in fluent)
            {
                sb.Append("        ").AppendLine(line);
            }
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static List<string> CollectFluentConfig(Catalog catalog)
    {
        // v1: no fluent config emitted. [OnDelete] handling is reserved for #4a.1.
        return new List<string>();
    }

    private static string Pluralise(string name)
    {
        if (name.EndsWith("y", StringComparison.Ordinal) && name.Length > 1 && !"aeiou".Contains(name[^2]))
            return name[..^1] + "ies";
        if (name.EndsWith("s", StringComparison.Ordinal) || name.EndsWith("x", StringComparison.Ordinal)
            || name.EndsWith("ch", StringComparison.Ordinal) || name.EndsWith("sh", StringComparison.Ordinal))
            return name + "es";
        return name + "s";
    }
}
