using System.Text.Json.Nodes;
using AspireForm.ApiCatalog;
using AspireForm.EntityCatalog;
using AspireForm.Providers;
using AspireForm.Providers.ApiEndpoints;
using AspireForm.Tests.ApiCatalog.Fixtures;
using AwesomeAssertions;
using Xunit;

namespace AspireForm.Tests.Providers.ApiEndpoints;

public sealed class ApiEndpointsModuleProviderTests
{
    private sealed class FakeCatalogService : IEndpointCatalogService
    {
        public required EndpointCatalog Catalog { get; init; }

        public Task<EndpointCatalog> ScanAsync(string csprojPath, CancellationToken ct) =>
            Task.FromResult(Catalog);

        public Task<EndpointMutationResult> MutateAsync(string csprojPath, EndpointChangeRequest request, CancellationToken ct) =>
            throw new NotSupportedException("MutateAsync should not be called from the provider plan path.");
    }

    private static PlanContext Ctx(JsonObject inputs, string appHostDir = ".") =>
        new("api", inputs, AppHostDirectory: appHostDir, ProjectName: "MyApp");

    private static EndpointCatalog EmptyCatalog() => new([], []);

    private static EndpointCatalog CatalogWithOneEndpoint() =>
        new([new EndpointInfo("BooksHandler", "GetBooks", "/books", "GET", null, null, [], [], [], "BooksHandler.cs")], []);

    [Fact]
    public void Type_and_kind_are_correct()
    {
        var p = new ApiEndpointsModuleProvider(new FakeCatalogService { Catalog = EmptyCatalog() });
        p.Type.Should().Be("api-endpoints");
        p.Kind.Should().Be(BlockKind.Module);
    }

    [Fact]
    public void Plan_throws_when_projectPath_is_missing()
    {
        var p = new ApiEndpointsModuleProvider(new FakeCatalogService { Catalog = EmptyCatalog() });
        var act = () => p.Plan(Ctx(new JsonObject()));
        act.Should().Throw<InvalidOperationException>()
            .WithMessage("*projectPath*required*");
    }

    [Fact]
    public void Plan_throws_when_project_file_does_not_exist()
    {
        var p = new ApiEndpointsModuleProvider(new FakeCatalogService { Catalog = EmptyCatalog() });
        var act = () => p.Plan(Ctx(new JsonObject { ["projectPath"] = "/nonexistent/Demo.csproj" }));
        act.Should().Throw<InvalidOperationException>()
            .WithMessage("*not found*");
    }

    [Fact]
    public void Plan_emits_managed_file_action_for_project_with_one_endpoint()
    {
        using var fix = new EndpointFixtureProjectBuilder("provider_one_ep");
        var p = new ApiEndpointsModuleProvider(new FakeCatalogService { Catalog = CatalogWithOneEndpoint() });
        var plan = p.Plan(Ctx(new JsonObject { ["projectPath"] = fix.CsprojPath }));

        plan.FileActions.Should().ContainSingle();
        var action = plan.FileActions[0];
        action.OwnershipMode.Should().Be(OwnershipMode.Managed);
        action.Path.Should().EndWith("_Endpoints.g.cs");

        // Verify emitted content contains the expected endpoint registration.
        var content = action.RenderContent();
        content.Should().Contain("// <auto-generated />");
        content.Should().Contain("MapAspireFormEndpoints");
        content.Should().Contain("BooksHandler.GetBooks");
    }

    [Fact]
    public void Plan_emits_empty_body_when_catalog_has_no_endpoints()
    {
        using var fix = new EndpointFixtureProjectBuilder("provider_empty");
        var p = new ApiEndpointsModuleProvider(new FakeCatalogService { Catalog = EmptyCatalog() });
        var plan = p.Plan(Ctx(new JsonObject { ["projectPath"] = fix.CsprojPath }));

        plan.FileActions.Should().ContainSingle();
        var content = plan.FileActions[0].RenderContent();
        content.Should().Contain("MapAspireFormEndpoints");
        // Empty body means only return app; inside the method.
        content.Should().Contain("return app;");
    }

    [Fact]
    public void Plan_uses_custom_outputPath_when_supplied()
    {
        using var fix = new EndpointFixtureProjectBuilder("provider_custom_out");
        var customOut = Path.Combine(fix.Root, "Custom", "Endpoints.g.cs");
        var p = new ApiEndpointsModuleProvider(new FakeCatalogService { Catalog = EmptyCatalog() });
        var plan = p.Plan(Ctx(new JsonObject
        {
            ["projectPath"] = fix.CsprojPath,
            ["outputPath"] = customOut,
        }));

        plan.FileActions[0].Path.Should().Be(customOut);
    }
}
